version: "3.9"

services:
  ec2-backend:
    container_name: ec2-backend
    entrypoint: "/usr/sbin/sshd -D"
    build: .
    tty: true
    ports:
      - "2222:22" 

  ec2-frontend:
    container_name: ec2-frontend
    entrypoint: "/usr/sbin/sshd -D"
    build: .
    tty: true
    ports:
      - "2223:22" 